global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "mautrix-wechat"
    static_configs:
      - targets: ["mautrix-wechat:9110"]
    metrics_path: /metrics
    scrape_interval: 10s
